### ISSUE TITLE
🎨 Configuring Vanilla Extract and Setting Tokens in Workshop workspace

### ISSUE THREAD

**Issue by dgd03146** [dgd03146/jung#22]
## 📌 Issue

Setting up vanilla extract tokens for design system

<br/>

## ☑️ To-do

- [x] Set up sprinkles
- [x] Set up global Styles
- [ ] Set up global font
- [x] Set up theme
