### ISSUE TITLE
Refactor Design System

### ISSUE THREAD

**Issue by dgd03146** [dgd03146/jung#41]
## 📌 Issue

- Refactoring Design system components
<br/>

## ☑️ To-do

- [x] Simplify the Box component and improve the type
- [x] Refactor all design system components type
- [x] Refactor Typography Component with compound pattern
- [x] Refactor Card Component and modify UI
- [x] Improve accessibility for components
