### ISSUE TITLE
Implement blog api with Tprc and Supabase in Server workspace

### ISSUE THREAD

**Issue by dgd03146** [dgd03146/jung#70]
## 📌 Issue

- Implement blog API with tRPC + Supabase

<br/>

## ☑️ To-do

- [x] Apply Turborepo to server workspace for the web workspace (Next.js 14 App Router)
- [x] Implement server-side rendering with tRPC to enable calling from server components
- [x] Apply Supabase keys in the environment file within Turborepo and commit changes
- [x] Handle errors in tRPC for the blog API
- [x] Refer to [TanStack React Query Advanced SSR Guide](https://tanstack.com/query/latest/docs/framework/react/guides/advanced-ssr) to apply React Query in server components
- [x] Set up shared configuration for the Query Client
- [x] Handle query keys
