### ISSUE TITLE
Set up Admin work space

### ISSUE THREAD

**Issue by dgd03146** [dgd03146/jung#73]
Set up Admin workspace

## 📌 Issue
- Initialize and configure Admin workspace in Turborepo

## ☑️ To-do
- [x] Implement FSD folder structure
- [x] Configure Trpc
- [x] Configure Tanstack Router
- [x] Configure Tanstack Query
- [x] Apply basic font styling with Vanilla Extract
